Revamp governance and others
bio-tools/biotoolsDocs pull request #38
Opened 2024-12-19 15:50 UTC by veitveit

Several adjustments and correction to represent the current setup and governance.

@hmenager @magnuspalmblad @matuskalas 
Please take a look at the changes in the [governance](https://github.com/bio-tools/biotoolsDocs/blob/384bde3ae6110a2f303e85b6048266ec2417f8bc/governance.rst) and [contributors](https://github.com/bio-tools/biotoolsDocs/blob/384bde3ae6110a2f303e85b6048266ec2417f8bc/contributors.rst). I tried to keep things simple and changes minimal.

I also removed the thematic editors from the governance, but still kept a now less concise page for a the [thematic editors](https://github.com/bio-tools/biotoolsDocs/blob/384bde3ae6110a2f303e85b6048266ec2417f8bc/editors_guide.rst)

@anitamnd 
FYI

2024-12-19 16:00 UTC, magnuspalmblad commented
Hi Veit,

In the governance document, I would write "node" and "platform" with capital "N" and "P" respectively in the first sentence. They are capitalized everywhere else.

In the contributors document, I suppose you could also put me down for "ontology development" and/or "bio.tools applications"?


All the best,

Magnus

From: Veit Schwämmle ***@***.***>
Sent: Thursday, December 19, 2024 4:51 PM
To: bio-tools/biotoolsDocs ***@***.***>
Cc: Palmblad, N.M. (CPM) ***@***.***>; Mention ***@***.***>
Subject: [bio-tools/biotoolsDocs] Revamp governance and others (PR #38)


Several adjustments and correction to represent the current setup and governance.

@hmenager<https://github.com/hmenager> @magnuspalmblad<https://github.com/magnuspalmblad> @matuskalas<https://github.com/matuskalas>
Please take a look at the changes in the governance<https://github.com/bio-tools/biotoolsDocs/blob/384bde3ae6110a2f303e85b6048266ec2417f8bc/governance.rst> and contributors<https://github.com/bio-tools/biotoolsDocs/blob/384bde3ae6110a2f303e85b6048266ec2417f8bc/contributors.rst>. I tried to keep things simple and changes minimal.

I also removed the thematic editors from the governance, but still kept a now less concise page for a the thematic editors<https://github.com/bio-tools/biotoolsDocs/blob/384bde3ae6110a2f303e85b6048266ec2417f8bc/editors_guide.rst>

@anitamnd<https://github.com/anitamnd>
FYI

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/bio-tools/biotoolsDocs/pull/38

Commit Summary

  *   13d6024<https://github.com/bio-tools/biotoolsDocs/pull/38/commits/13d6024d43966f0d2141775a9fa55dd5fb49f112> Update governance.rst
  *   4a47aad<https://github.com/bio-tools/biotoolsDocs/pull/38/commits/4a47aada8ae905d2ae30389414dab876521b1956> Update contributors.rst
  *   4974dba<https://github.com/bio-tools/biotoolsDocs/pull/38/commits/4974dba75c4db62514eab4ac4c91ac95de37d737> Update curators_guide.rst
  *   e102cf2<https://github.com/bio-tools/biotoolsDocs/pull/38/commits/e102cf20633bf328e2de1b5f8bfa3bcf9d937df1> Update editors_guide.rst
  *   9a3f3ae<https://github.com/bio-tools/biotoolsDocs/pull/38/commits/9a3f3aec04c883dfc6a6741309215e46c5363bc2> Update studentships.rst
  *   7674f19<https://github.com/bio-tools/biotoolsDocs/pull/38/commits/7674f19516554d96ac32f0cd2c3fc7d56c000657> Update support.rst
  *   384bde3<https://github.com/bio-tools/biotoolsDocs/pull/38/commits/384bde3ae6110a2f303e85b6048266ec2417f8bc> Update code.rst

File Changes

(7 files<https://github.com/bio-tools/biotoolsDocs/pull/38/files>)

  *   M code.rst<https://github.com/bio-tools/biotoolsDocs/pull/38/files#diff-e597ab98463b63450f98f66d6d80286670dfce01533c4beabc06899cfaa5a1bb> (2)
  *   M contributors.rst<https://github.com/bio-tools/biotoolsDocs/pull/38/files#diff-38cd904d3080d9acc03cab51030a6effa7d386b55c30519ef82ef47a795c75a2> (52)
  *   M curators_guide.rst<https://github.com/bio-tools/biotoolsDocs/pull/38/files#diff-06c6ee64d5e3989d46032d02f4ca75b57ab11ce78c7d7904eff59ff8f3beec52> (40)
  *   M editors_guide.rst<https://github.com/bio-tools/biotoolsDocs/pull/38/files#diff-8a5c22f621622dfec229394817b5a44e6bbde148abd8665830ea817db874ec24> (34)
  *   M governance.rst<https://github.com/bio-tools/biotoolsDocs/pull/38/files#diff-ec4786cfbb1649e86f413a0628f0dd373966ade53e08fe2771191260a94d38b4> (13)
  *   M studentships.rst<https://github.com/bio-tools/biotoolsDocs/pull/38/files#diff-47cdb21dfc3980351935863866b950f79147a111d3ba79b274f6b8639dca9f99> (8)
  *   M support.rst<https://github.com/bio-tools/biotoolsDocs/pull/38/files#diff-9b3288354cc7045c4d25b7ee06895cf52ab41c09efebacf32415c49727478d2e> (2)

Patch Links:

  *   https://github.com/bio-tools/biotoolsDocs/pull/38.patch
  *   https://github.com/bio-tools/biotoolsDocs/pull/38.diff

-
Reply to this email directly, view it on GitHub<https://github.com/bio-tools/biotoolsDocs/pull/38>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AD2WZHMSIQOSZW3D5EBXJKD2GLTPTAVCNFSM6AAAAABT5JCQ7GVHI2DSMVQWIX3LMV43ASLTON2WKOZSG42TANZVG42DMMQ>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2024-12-19 17:28 UTC, veitveit commented
Done :+1:

2024-12-19 17:53 UTC, hmenager requested changes
I'm done. I have a few comments (see review details), but these changes are very welcome, thanks a lot @veitveit !

2024-12-19 17:53 UTC, hmenager commented on code.rst
> +The system is packaged in multiple docker containers to achieve a more reproducible, environment-independent local deployment solution.
I would just remove this note, the documentation for the local docker-compose deployment is just below.

2024-12-19 17:53 UTC, hmenager commented on contributors.rst
> +- Kenzo Hillion (Institut Pasteur, FR) - **workbench integration**,
full name is Kenzo-Hugo Hillion :)

2024-12-19 17:53 UTC, hmenager commented on curators_guide.rst
> +   If you plan to register multiple entries *en masse*, please discuss this first with `bio.tools admin <mailto:support-bio-tools@sdu.dkf>`_.
the trailing `f` in support-bio-tools@sdu.dkf is a typo, right?

2024-12-19 17:53 UTC, hmenager commented on curators_guide.rst
> +   Some high-level "organisational" concepts defined in EDAM are intended primarily to structure the hierarchy, and are not intended for annotation in *bio.tools*. They are defined in `EDAM.owl <http
should be `<notRecommendedForAnnotation rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</notRecommendedForAnnotation>`. And might need some validation from @matuskalas.

2024-12-19 17:53 UTC, hmenager commented on editors_guide.rst
> +Former thematic editors
I would remove "former" members from this section, to keep it lighter (just keep them in former contributors section)

2024-12-19 17:53 UTC, hmenager commented on studentships.rst
> +`ELIXIR Denmark <http://elixir-denmark.org/>`_ - the coordinating node of the *bio.tools* project - earmars funds (as available) to support studentships to work on curation-focussed mini-projects for
Are such studentships still funded by ELIXIR-DK? Also, typo with a missing k on earmarks.

2024-12-19 17:53 UTC, hmenager commented on studentships.rst
> +Former Proposals
Same here, I'd just remove "former stuff/history" from there to make maintenance of this document more manageable

2024-12-20 08:38 UTC, veitveit commented on curators_guide.rst
> +   Some high-level "organisational" concepts defined in EDAM are intended primarily to structure the hierarchy, and are not intended for annotation in *bio.tools*. They are defined in `EDAM.owl <http
Thanks, I changed that now.

2024-12-20 09:06 UTC, veitveit commented on studentships.rst
> +`ELIXIR Denmark <http://elixir-denmark.org/>`_ - the coordinating node of the *bio.tools* project - earmars funds (as available) to support studentships to work on curation-focussed mini-projects for
Yes and no. Mostly repurposed funding from either local or ELIXIR resources. Until now the students have been supervised by Jon, Hans and I. Therefore the ELIXIR-DK tag. 

Or am I wrong here?

2025-01-08 16:58 UTC, merged